import "./globals.css";
import './blob.css';  
import BlobBackground from './components/BlobBackground';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body>
        <BlobBackground /> {/* Background blob stays behind */}
        <div className="glass-overlay"></div>
        <main className="relative z-20"> {/* Page content */}
          {children}  {/* This renders the content of page.js */}
        </main>
      </body>
    </html>
  );
}