import "./globals.css";
import './blob.css';  
import { Roboto } from 'next/font/google';
import BlobBackground from './components/BlobBackground';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export default function Layout({ children }) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <BlobBackground /> {/* Background blob stays behind */}
        <main className="relative z-10"> {/* Page content */}
          {children}  {/* This renders the content of page.js */}
        </main>
      </body>
    </html>
  );
}