import "./globals.css";
import { Roboto } from 'next/font/google';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: ['400', '500', '700'], // You can add more or fewer weights depending on your design
  subsets: ['latin'], // Choose the subset that matches your needs
  display: 'swap', // Optional: ensures fonts display fallback content while loading
});


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        {children}
      </body>
    </html>
  );
}
