// Auto-generated file - do not edit directly
// Generated by scripts/generate-projects-data.js

import portfolioMDX from './portfolio.mdx';

export const projectsData = [
  {
    id: 'portfolio',
    title: "Portfolio Website",
    description: "A responsive portfolio website built with React and Tailwind CSS",
    github: "https://github.com/dillguill/dillguill.github.io",
    demo: "https://dillguill.github.io",
    tech: ["React","Tailwind CSS","Framer Motion"],
    component: portfolioMDX,
  },
];
